name: Firebase Web CI

on: 
  push:
    branches: 
      - main
jobs:
  Build_Deploy_Web:
    runs-on: ubuntu-latest
  
    steps:
      ## Checkout current branch
      - uses: actions/checkout@v1

      ## Install dependencies
      - name: yarn install
        run: |
          yarn 
      - uses: FirebaseExtended/action-hosting-deploy@v0
      ## Build & Deploy
      - name: Build & Deploy
        run: |
          yarn build
          firebase deploy --only hosting --token ${{ SECRETS.FIREBASE_TOKEN }} 
